# Config package initialization
from .settings import (
    # Paths
    BASE_DIR,
    TEMP_FOLDER,
    PROCESSED_FILE,
    TOKEN_PATH,
    CREDENTIALS_PATH,
    
    # DoodStream
    DOODSTREAM_API_KEY,
    DOODSTREAM_API_BASE_URL,
    DOODSTREAM_WATCH_BASE_URL,
    DOODSTREAM_DOWNLOAD_BASE_URL,
    DOODSTREAM_API_DELAY,
    
    # Google
    GOOGLE_SHEET_ID,
    GOOGLE_SCOPES,
    
    # Source Website
    CATEGORY_URL,
    CATEGORY_NAME,
    BASE_URL,
    
    # Headers
    DEFAULT_HEADERS,
    
    # Processing Settings
    MAX_RETRIES,
    RETRY_DELAY,
    VIDEO_MIN_SIZE,
    REQUEST_TIMEOUT,
    
    # Sheet
    SHEET_HEADERS,
    SHEET_RANGE,
    
    # Logging
    LOG_LEVEL,
    LOG_FORMAT,
)

__all__ = [
    'BASE_DIR',
    'TEMP_FOLDER',
    'PROCESSED_FILE',
    'TOKEN_PATH',
    'CREDENTIALS_PATH',
    'DOODSTREAM_API_KEY',
    'DOODSTREAM_API_BASE_URL',
    'DOODSTREAM_WATCH_BASE_URL',
    'DOODSTREAM_DOWNLOAD_BASE_URL',
    'DOODSTREAM_API_DELAY',
    'GOOGLE_SHEET_ID',
    'GOOGLE_SCOPES',
    'CATEGORY_URL',
    'CATEGORY_NAME',
    'BASE_URL',
    'DEFAULT_HEADERS',
    'MAX_RETRIES',
    'RETRY_DELAY',
    'VIDEO_MIN_SIZE',
    'REQUEST_TIMEOUT',
    'SHEET_HEADERS',
    'SHEET_RANGE',
    'LOG_LEVEL',
    'LOG_FORMAT',
]
